// v1.v

// Generated using ACDS version 13.1 162 at 2026.05.18.12:07:35

`timescale 1 ps / 1 ps
module v1 (
		input  wire        clk_clk,          //        clk.clk
		input  wire        reset_reset_n,    //      reset.reset_n
		output wire [7:0]  led_export,       //        led.export
		input  wire [7:0]  sw_export,        //         sw.export
		output wire [12:0] sdram_wire_addr,  // sdram_wire.addr
		output wire [1:0]  sdram_wire_ba,    //           .ba
		output wire        sdram_wire_cas_n, //           .cas_n
		output wire        sdram_wire_cke,   //           .cke
		output wire        sdram_wire_cs_n,  //           .cs_n
		inout  wire [15:0] sdram_wire_dq,    //           .dq
		output wire [1:0]  sdram_wire_dqm,   //           .dqm
		output wire        sdram_wire_ras_n, //           .ras_n
		output wire        sdram_wire_we_n,  //           .we_n
		output wire        sdram_clk_clk,    //  sdram_clk.clk
		output wire        motor_p_r_export, //  motor_p_r.export
		output wire        motor_n_r_export, //  motor_n_r.export
		output wire        motor_p_l_export, //  motor_p_l.export
		output wire        motor_n_l_export  //  motor_n_l.export
	);

	wire         clocks_sys_clk_clk;                                      // clocks:sys_clk -> [CPU:clk, JTAG:clk, LED:clk, MEMOIRE:clk, SDRAM:clk, SW:clk, irq_mapper:clk, mm_interconnect_0:clocks_sys_clk_clk, rst_controller:clk]
	wire         mm_interconnect_0_cpu_jtag_debug_module_waitrequest;     // CPU:jtag_debug_module_waitrequest -> mm_interconnect_0:CPU_jtag_debug_module_waitrequest
	wire  [31:0] mm_interconnect_0_cpu_jtag_debug_module_writedata;       // mm_interconnect_0:CPU_jtag_debug_module_writedata -> CPU:jtag_debug_module_writedata
	wire   [8:0] mm_interconnect_0_cpu_jtag_debug_module_address;         // mm_interconnect_0:CPU_jtag_debug_module_address -> CPU:jtag_debug_module_address
	wire         mm_interconnect_0_cpu_jtag_debug_module_write;           // mm_interconnect_0:CPU_jtag_debug_module_write -> CPU:jtag_debug_module_write
	wire         mm_interconnect_0_cpu_jtag_debug_module_read;            // mm_interconnect_0:CPU_jtag_debug_module_read -> CPU:jtag_debug_module_read
	wire  [31:0] mm_interconnect_0_cpu_jtag_debug_module_readdata;        // CPU:jtag_debug_module_readdata -> mm_interconnect_0:CPU_jtag_debug_module_readdata
	wire         mm_interconnect_0_cpu_jtag_debug_module_debugaccess;     // mm_interconnect_0:CPU_jtag_debug_module_debugaccess -> CPU:jtag_debug_module_debugaccess
	wire   [3:0] mm_interconnect_0_cpu_jtag_debug_module_byteenable;      // mm_interconnect_0:CPU_jtag_debug_module_byteenable -> CPU:jtag_debug_module_byteenable
	wire  [31:0] mm_interconnect_0_memoire_s1_writedata;                  // mm_interconnect_0:MEMOIRE_s1_writedata -> MEMOIRE:writedata
	wire   [9:0] mm_interconnect_0_memoire_s1_address;                    // mm_interconnect_0:MEMOIRE_s1_address -> MEMOIRE:address
	wire         mm_interconnect_0_memoire_s1_chipselect;                 // mm_interconnect_0:MEMOIRE_s1_chipselect -> MEMOIRE:chipselect
	wire         mm_interconnect_0_memoire_s1_clken;                      // mm_interconnect_0:MEMOIRE_s1_clken -> MEMOIRE:clken
	wire         mm_interconnect_0_memoire_s1_write;                      // mm_interconnect_0:MEMOIRE_s1_write -> MEMOIRE:write
	wire  [31:0] mm_interconnect_0_memoire_s1_readdata;                   // MEMOIRE:readdata -> mm_interconnect_0:MEMOIRE_s1_readdata
	wire   [3:0] mm_interconnect_0_memoire_s1_byteenable;                 // mm_interconnect_0:MEMOIRE_s1_byteenable -> MEMOIRE:byteenable
	wire         cpu_instruction_master_waitrequest;                      // mm_interconnect_0:CPU_instruction_master_waitrequest -> CPU:i_waitrequest
	wire  [26:0] cpu_instruction_master_address;                          // CPU:i_address -> mm_interconnect_0:CPU_instruction_master_address
	wire         cpu_instruction_master_read;                             // CPU:i_read -> mm_interconnect_0:CPU_instruction_master_read
	wire  [31:0] cpu_instruction_master_readdata;                         // mm_interconnect_0:CPU_instruction_master_readdata -> CPU:i_readdata
	wire         cpu_data_master_waitrequest;                             // mm_interconnect_0:CPU_data_master_waitrequest -> CPU:d_waitrequest
	wire  [31:0] cpu_data_master_writedata;                               // CPU:d_writedata -> mm_interconnect_0:CPU_data_master_writedata
	wire  [26:0] cpu_data_master_address;                                 // CPU:d_address -> mm_interconnect_0:CPU_data_master_address
	wire         cpu_data_master_write;                                   // CPU:d_write -> mm_interconnect_0:CPU_data_master_write
	wire         cpu_data_master_read;                                    // CPU:d_read -> mm_interconnect_0:CPU_data_master_read
	wire  [31:0] cpu_data_master_readdata;                                // mm_interconnect_0:CPU_data_master_readdata -> CPU:d_readdata
	wire         cpu_data_master_debugaccess;                             // CPU:jtag_debug_module_debugaccess_to_roms -> mm_interconnect_0:CPU_data_master_debugaccess
	wire   [3:0] cpu_data_master_byteenable;                              // CPU:d_byteenable -> mm_interconnect_0:CPU_data_master_byteenable
	wire   [1:0] mm_interconnect_0_sw_s1_address;                         // mm_interconnect_0:SW_s1_address -> SW:address
	wire  [31:0] mm_interconnect_0_sw_s1_readdata;                        // SW:readdata -> mm_interconnect_0:SW_s1_readdata
	wire         mm_interconnect_0_jtag_avalon_jtag_slave_waitrequest;    // JTAG:av_waitrequest -> mm_interconnect_0:JTAG_avalon_jtag_slave_waitrequest
	wire  [31:0] mm_interconnect_0_jtag_avalon_jtag_slave_writedata;      // mm_interconnect_0:JTAG_avalon_jtag_slave_writedata -> JTAG:av_writedata
	wire   [0:0] mm_interconnect_0_jtag_avalon_jtag_slave_address;        // mm_interconnect_0:JTAG_avalon_jtag_slave_address -> JTAG:av_address
	wire         mm_interconnect_0_jtag_avalon_jtag_slave_chipselect;     // mm_interconnect_0:JTAG_avalon_jtag_slave_chipselect -> JTAG:av_chipselect
	wire         mm_interconnect_0_jtag_avalon_jtag_slave_write;          // mm_interconnect_0:JTAG_avalon_jtag_slave_write -> JTAG:av_write_n
	wire         mm_interconnect_0_jtag_avalon_jtag_slave_read;           // mm_interconnect_0:JTAG_avalon_jtag_slave_read -> JTAG:av_read_n
	wire  [31:0] mm_interconnect_0_jtag_avalon_jtag_slave_readdata;       // JTAG:av_readdata -> mm_interconnect_0:JTAG_avalon_jtag_slave_readdata
	wire  [31:0] mm_interconnect_0_pwm_motor_0_avalon_slave_0_writedata;  // mm_interconnect_0:pwm_motor_0_avalon_slave_0_writedata -> pwm_motor_0:writedata
	wire   [1:0] mm_interconnect_0_pwm_motor_0_avalon_slave_0_address;    // mm_interconnect_0:pwm_motor_0_avalon_slave_0_address -> pwm_motor_0:address
	wire         mm_interconnect_0_pwm_motor_0_avalon_slave_0_chipselect; // mm_interconnect_0:pwm_motor_0_avalon_slave_0_chipselect -> pwm_motor_0:chipselect
	wire         mm_interconnect_0_pwm_motor_0_avalon_slave_0_write;      // mm_interconnect_0:pwm_motor_0_avalon_slave_0_write -> pwm_motor_0:write
	wire         mm_interconnect_0_pwm_motor_0_avalon_slave_0_read;       // mm_interconnect_0:pwm_motor_0_avalon_slave_0_read -> pwm_motor_0:read
	wire  [31:0] mm_interconnect_0_pwm_motor_0_avalon_slave_0_readdata;   // pwm_motor_0:readdata -> mm_interconnect_0:pwm_motor_0_avalon_slave_0_readdata
	wire  [31:0] mm_interconnect_0_led_s1_writedata;                      // mm_interconnect_0:LED_s1_writedata -> LED:writedata
	wire   [1:0] mm_interconnect_0_led_s1_address;                        // mm_interconnect_0:LED_s1_address -> LED:address
	wire         mm_interconnect_0_led_s1_chipselect;                     // mm_interconnect_0:LED_s1_chipselect -> LED:chipselect
	wire         mm_interconnect_0_led_s1_write;                          // mm_interconnect_0:LED_s1_write -> LED:write_n
	wire  [31:0] mm_interconnect_0_led_s1_readdata;                       // LED:readdata -> mm_interconnect_0:LED_s1_readdata
	wire         mm_interconnect_0_sdram_s1_waitrequest;                  // SDRAM:za_waitrequest -> mm_interconnect_0:SDRAM_s1_waitrequest
	wire  [15:0] mm_interconnect_0_sdram_s1_writedata;                    // mm_interconnect_0:SDRAM_s1_writedata -> SDRAM:az_data
	wire  [23:0] mm_interconnect_0_sdram_s1_address;                      // mm_interconnect_0:SDRAM_s1_address -> SDRAM:az_addr
	wire         mm_interconnect_0_sdram_s1_chipselect;                   // mm_interconnect_0:SDRAM_s1_chipselect -> SDRAM:az_cs
	wire         mm_interconnect_0_sdram_s1_write;                        // mm_interconnect_0:SDRAM_s1_write -> SDRAM:az_wr_n
	wire         mm_interconnect_0_sdram_s1_read;                         // mm_interconnect_0:SDRAM_s1_read -> SDRAM:az_rd_n
	wire  [15:0] mm_interconnect_0_sdram_s1_readdata;                     // SDRAM:za_data -> mm_interconnect_0:SDRAM_s1_readdata
	wire         mm_interconnect_0_sdram_s1_readdatavalid;                // SDRAM:za_valid -> mm_interconnect_0:SDRAM_s1_readdatavalid
	wire   [1:0] mm_interconnect_0_sdram_s1_byteenable;                   // mm_interconnect_0:SDRAM_s1_byteenable -> SDRAM:az_be_n
	wire         irq_mapper_receiver0_irq;                                // JTAG:av_irq -> irq_mapper:receiver0_irq
	wire  [31:0] cpu_d_irq_irq;                                           // irq_mapper:sender_irq -> CPU:d_irq
	wire         rst_controller_reset_out_reset;                          // rst_controller:reset_out -> [CPU:reset_n, JTAG:rst_n, LED:reset_n, MEMOIRE:reset, SDRAM:reset_n, SW:reset_n, irq_mapper:reset, mm_interconnect_0:CPU_reset_n_reset_bridge_in_reset_reset, rst_translator:in_reset]
	wire         rst_controller_reset_out_reset_req;                      // rst_controller:reset_req -> [CPU:reset_req, MEMOIRE:reset_req, rst_translator:reset_req_in]
	wire         cpu_jtag_debug_module_reset_reset;                       // CPU:jtag_debug_module_resetrequest -> [rst_controller:reset_in1, rst_controller_001:reset_in1]
	wire         rst_controller_001_reset_out_reset;                      // rst_controller_001:reset_out -> clocks:reset
	wire         rst_controller_002_reset_out_reset;                      // rst_controller_002:reset_out -> [mm_interconnect_0:pwm_motor_0_reset_sink_reset_bridge_in_reset_reset, pwm_motor_0:reset_n]

	v1_CPU cpu (
		.clk                                   (clocks_sys_clk_clk),                                  //                       clk.clk
		.reset_n                               (~rst_controller_reset_out_reset),                     //                   reset_n.reset_n
		.reset_req                             (rst_controller_reset_out_reset_req),                  //                          .reset_req
		.d_address                             (cpu_data_master_address),                             //               data_master.address
		.d_byteenable                          (cpu_data_master_byteenable),                          //                          .byteenable
		.d_read                                (cpu_data_master_read),                                //                          .read
		.d_readdata                            (cpu_data_master_readdata),                            //                          .readdata
		.d_waitrequest                         (cpu_data_master_waitrequest),                         //                          .waitrequest
		.d_write                               (cpu_data_master_write),                               //                          .write
		.d_writedata                           (cpu_data_master_writedata),                           //                          .writedata
		.jtag_debug_module_debugaccess_to_roms (cpu_data_master_debugaccess),                         //                          .debugaccess
		.i_address                             (cpu_instruction_master_address),                      //        instruction_master.address
		.i_read                                (cpu_instruction_master_read),                         //                          .read
		.i_readdata                            (cpu_instruction_master_readdata),                     //                          .readdata
		.i_waitrequest                         (cpu_instruction_master_waitrequest),                  //                          .waitrequest
		.d_irq                                 (cpu_d_irq_irq),                                       //                     d_irq.irq
		.jtag_debug_module_resetrequest        (cpu_jtag_debug_module_reset_reset),                   //   jtag_debug_module_reset.reset
		.jtag_debug_module_address             (mm_interconnect_0_cpu_jtag_debug_module_address),     //         jtag_debug_module.address
		.jtag_debug_module_byteenable          (mm_interconnect_0_cpu_jtag_debug_module_byteenable),  //                          .byteenable
		.jtag_debug_module_debugaccess         (mm_interconnect_0_cpu_jtag_debug_module_debugaccess), //                          .debugaccess
		.jtag_debug_module_read                (mm_interconnect_0_cpu_jtag_debug_module_read),        //                          .read
		.jtag_debug_module_readdata            (mm_interconnect_0_cpu_jtag_debug_module_readdata),    //                          .readdata
		.jtag_debug_module_waitrequest         (mm_interconnect_0_cpu_jtag_debug_module_waitrequest), //                          .waitrequest
		.jtag_debug_module_write               (mm_interconnect_0_cpu_jtag_debug_module_write),       //                          .write
		.jtag_debug_module_writedata           (mm_interconnect_0_cpu_jtag_debug_module_writedata),   //                          .writedata
		.no_ci_readra                          ()                                                     // custom_instruction_master.readra
	);

	v1_MEMOIRE memoire (
		.clk        (clocks_sys_clk_clk),                      //   clk1.clk
		.address    (mm_interconnect_0_memoire_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_memoire_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_memoire_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_memoire_s1_write),      //       .write
		.readdata   (mm_interconnect_0_memoire_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_memoire_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_memoire_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),          // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req)       //       .reset_req
	);

	v1_SW sw (
		.clk      (clocks_sys_clk_clk),               //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),  //               reset.reset_n
		.address  (mm_interconnect_0_sw_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_sw_s1_readdata), //                    .readdata
		.in_port  (sw_export)                         // external_connection.export
	);

	v1_LED led (
		.clk        (clocks_sys_clk_clk),                  //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),     //               reset.reset_n
		.address    (mm_interconnect_0_led_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_led_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_led_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_led_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_led_s1_readdata),   //                    .readdata
		.out_port   (led_export)                           // external_connection.export
	);

	v1_JTAG jtag (
		.clk            (clocks_sys_clk_clk),                                   //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                      //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_jtag_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_jtag_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_jtag_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_jtag_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_jtag_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_jtag_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_jtag_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                              //               irq.irq
	);

	v1_SDRAM sdram (
		.clk            (clocks_sys_clk_clk),                       //   clk.clk
		.reset_n        (~rst_controller_reset_out_reset),          // reset.reset_n
		.az_addr        (mm_interconnect_0_sdram_s1_address),       //    s1.address
		.az_be_n        (~mm_interconnect_0_sdram_s1_byteenable),   //      .byteenable_n
		.az_cs          (mm_interconnect_0_sdram_s1_chipselect),    //      .chipselect
		.az_data        (mm_interconnect_0_sdram_s1_writedata),     //      .writedata
		.az_rd_n        (~mm_interconnect_0_sdram_s1_read),         //      .read_n
		.az_wr_n        (~mm_interconnect_0_sdram_s1_write),        //      .write_n
		.za_data        (mm_interconnect_0_sdram_s1_readdata),      //      .readdata
		.za_valid       (mm_interconnect_0_sdram_s1_readdatavalid), //      .readdatavalid
		.za_waitrequest (mm_interconnect_0_sdram_s1_waitrequest),   //      .waitrequest
		.zs_addr        (sdram_wire_addr),                          //  wire.export
		.zs_ba          (sdram_wire_ba),                            //      .export
		.zs_cas_n       (sdram_wire_cas_n),                         //      .export
		.zs_cke         (sdram_wire_cke),                           //      .export
		.zs_cs_n        (sdram_wire_cs_n),                          //      .export
		.zs_dq          (sdram_wire_dq),                            //      .export
		.zs_dqm         (sdram_wire_dqm),                           //      .export
		.zs_ras_n       (sdram_wire_ras_n),                         //      .export
		.zs_we_n        (sdram_wire_we_n)                           //      .export
	);

	v1_clocks clocks (
		.CLOCK_50    (clk_clk),                            //       clk_in_primary.clk
		.reset       (rst_controller_001_reset_out_reset), // clk_in_primary_reset.reset
		.sys_clk     (clocks_sys_clk_clk),                 //              sys_clk.clk
		.sys_reset_n (),                                   //        sys_clk_reset.reset_n
		.SDRAM_CLK   (sdram_clk_clk)                       //            sdram_clk.clk
	);

	PWM_avalon_wrapper pwm_motor_0 (
		.address      (mm_interconnect_0_pwm_motor_0_avalon_slave_0_address),    // avalon_slave_0.address
		.write        (mm_interconnect_0_pwm_motor_0_avalon_slave_0_write),      //               .write
		.read         (mm_interconnect_0_pwm_motor_0_avalon_slave_0_read),       //               .read
		.writedata    (mm_interconnect_0_pwm_motor_0_avalon_slave_0_writedata),  //               .writedata
		.readdata     (mm_interconnect_0_pwm_motor_0_avalon_slave_0_readdata),   //               .readdata
		.chipselect   (mm_interconnect_0_pwm_motor_0_avalon_slave_0_chipselect), //               .chipselect
		.dc_motor_p_R (motor_p_r_export),                                        //    conduit_end.export
		.dc_motor_n_R (motor_n_r_export),                                        //  conduit_end_1.export
		.dc_motor_p_L (motor_p_l_export),                                        //  conduit_end_2.export
		.dc_motor_n_L (motor_n_l_export),                                        //  conduit_end_3.export
		.clk          (clk_clk),                                                 //     clock_sink.clk
		.reset_n      (~rst_controller_002_reset_out_reset)                      //     reset_sink.reset_n
	);

	v1_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                                      (clk_clk),                                                 //                                    clk_0_clk.clk
		.clocks_sys_clk_clk                                 (clocks_sys_clk_clk),                                      //                               clocks_sys_clk.clk
		.CPU_reset_n_reset_bridge_in_reset_reset            (rst_controller_reset_out_reset),                          //            CPU_reset_n_reset_bridge_in_reset.reset
		.pwm_motor_0_reset_sink_reset_bridge_in_reset_reset (rst_controller_002_reset_out_reset),                      // pwm_motor_0_reset_sink_reset_bridge_in_reset.reset
		.CPU_data_master_address                            (cpu_data_master_address),                                 //                              CPU_data_master.address
		.CPU_data_master_waitrequest                        (cpu_data_master_waitrequest),                             //                                             .waitrequest
		.CPU_data_master_byteenable                         (cpu_data_master_byteenable),                              //                                             .byteenable
		.CPU_data_master_read                               (cpu_data_master_read),                                    //                                             .read
		.CPU_data_master_readdata                           (cpu_data_master_readdata),                                //                                             .readdata
		.CPU_data_master_write                              (cpu_data_master_write),                                   //                                             .write
		.CPU_data_master_writedata                          (cpu_data_master_writedata),                               //                                             .writedata
		.CPU_data_master_debugaccess                        (cpu_data_master_debugaccess),                             //                                             .debugaccess
		.CPU_instruction_master_address                     (cpu_instruction_master_address),                          //                       CPU_instruction_master.address
		.CPU_instruction_master_waitrequest                 (cpu_instruction_master_waitrequest),                      //                                             .waitrequest
		.CPU_instruction_master_read                        (cpu_instruction_master_read),                             //                                             .read
		.CPU_instruction_master_readdata                    (cpu_instruction_master_readdata),                         //                                             .readdata
		.CPU_jtag_debug_module_address                      (mm_interconnect_0_cpu_jtag_debug_module_address),         //                        CPU_jtag_debug_module.address
		.CPU_jtag_debug_module_write                        (mm_interconnect_0_cpu_jtag_debug_module_write),           //                                             .write
		.CPU_jtag_debug_module_read                         (mm_interconnect_0_cpu_jtag_debug_module_read),            //                                             .read
		.CPU_jtag_debug_module_readdata                     (mm_interconnect_0_cpu_jtag_debug_module_readdata),        //                                             .readdata
		.CPU_jtag_debug_module_writedata                    (mm_interconnect_0_cpu_jtag_debug_module_writedata),       //                                             .writedata
		.CPU_jtag_debug_module_byteenable                   (mm_interconnect_0_cpu_jtag_debug_module_byteenable),      //                                             .byteenable
		.CPU_jtag_debug_module_waitrequest                  (mm_interconnect_0_cpu_jtag_debug_module_waitrequest),     //                                             .waitrequest
		.CPU_jtag_debug_module_debugaccess                  (mm_interconnect_0_cpu_jtag_debug_module_debugaccess),     //                                             .debugaccess
		.JTAG_avalon_jtag_slave_address                     (mm_interconnect_0_jtag_avalon_jtag_slave_address),        //                       JTAG_avalon_jtag_slave.address
		.JTAG_avalon_jtag_slave_write                       (mm_interconnect_0_jtag_avalon_jtag_slave_write),          //                                             .write
		.JTAG_avalon_jtag_slave_read                        (mm_interconnect_0_jtag_avalon_jtag_slave_read),           //                                             .read
		.JTAG_avalon_jtag_slave_readdata                    (mm_interconnect_0_jtag_avalon_jtag_slave_readdata),       //                                             .readdata
		.JTAG_avalon_jtag_slave_writedata                   (mm_interconnect_0_jtag_avalon_jtag_slave_writedata),      //                                             .writedata
		.JTAG_avalon_jtag_slave_waitrequest                 (mm_interconnect_0_jtag_avalon_jtag_slave_waitrequest),    //                                             .waitrequest
		.JTAG_avalon_jtag_slave_chipselect                  (mm_interconnect_0_jtag_avalon_jtag_slave_chipselect),     //                                             .chipselect
		.LED_s1_address                                     (mm_interconnect_0_led_s1_address),                        //                                       LED_s1.address
		.LED_s1_write                                       (mm_interconnect_0_led_s1_write),                          //                                             .write
		.LED_s1_readdata                                    (mm_interconnect_0_led_s1_readdata),                       //                                             .readdata
		.LED_s1_writedata                                   (mm_interconnect_0_led_s1_writedata),                      //                                             .writedata
		.LED_s1_chipselect                                  (mm_interconnect_0_led_s1_chipselect),                     //                                             .chipselect
		.MEMOIRE_s1_address                                 (mm_interconnect_0_memoire_s1_address),                    //                                   MEMOIRE_s1.address
		.MEMOIRE_s1_write                                   (mm_interconnect_0_memoire_s1_write),                      //                                             .write
		.MEMOIRE_s1_readdata                                (mm_interconnect_0_memoire_s1_readdata),                   //                                             .readdata
		.MEMOIRE_s1_writedata                               (mm_interconnect_0_memoire_s1_writedata),                  //                                             .writedata
		.MEMOIRE_s1_byteenable                              (mm_interconnect_0_memoire_s1_byteenable),                 //                                             .byteenable
		.MEMOIRE_s1_chipselect                              (mm_interconnect_0_memoire_s1_chipselect),                 //                                             .chipselect
		.MEMOIRE_s1_clken                                   (mm_interconnect_0_memoire_s1_clken),                      //                                             .clken
		.pwm_motor_0_avalon_slave_0_address                 (mm_interconnect_0_pwm_motor_0_avalon_slave_0_address),    //                   pwm_motor_0_avalon_slave_0.address
		.pwm_motor_0_avalon_slave_0_write                   (mm_interconnect_0_pwm_motor_0_avalon_slave_0_write),      //                                             .write
		.pwm_motor_0_avalon_slave_0_read                    (mm_interconnect_0_pwm_motor_0_avalon_slave_0_read),       //                                             .read
		.pwm_motor_0_avalon_slave_0_readdata                (mm_interconnect_0_pwm_motor_0_avalon_slave_0_readdata),   //                                             .readdata
		.pwm_motor_0_avalon_slave_0_writedata               (mm_interconnect_0_pwm_motor_0_avalon_slave_0_writedata),  //                                             .writedata
		.pwm_motor_0_avalon_slave_0_chipselect              (mm_interconnect_0_pwm_motor_0_avalon_slave_0_chipselect), //                                             .chipselect
		.SDRAM_s1_address                                   (mm_interconnect_0_sdram_s1_address),                      //                                     SDRAM_s1.address
		.SDRAM_s1_write                                     (mm_interconnect_0_sdram_s1_write),                        //                                             .write
		.SDRAM_s1_read                                      (mm_interconnect_0_sdram_s1_read),                         //                                             .read
		.SDRAM_s1_readdata                                  (mm_interconnect_0_sdram_s1_readdata),                     //                                             .readdata
		.SDRAM_s1_writedata                                 (mm_interconnect_0_sdram_s1_writedata),                    //                                             .writedata
		.SDRAM_s1_byteenable                                (mm_interconnect_0_sdram_s1_byteenable),                   //                                             .byteenable
		.SDRAM_s1_readdatavalid                             (mm_interconnect_0_sdram_s1_readdatavalid),                //                                             .readdatavalid
		.SDRAM_s1_waitrequest                               (mm_interconnect_0_sdram_s1_waitrequest),                  //                                             .waitrequest
		.SDRAM_s1_chipselect                                (mm_interconnect_0_sdram_s1_chipselect),                   //                                             .chipselect
		.SW_s1_address                                      (mm_interconnect_0_sw_s1_address),                         //                                        SW_s1.address
		.SW_s1_readdata                                     (mm_interconnect_0_sw_s1_readdata)                         //                                             .readdata
	);

	v1_irq_mapper irq_mapper (
		.clk           (clocks_sys_clk_clk),             //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.sender_irq    (cpu_d_irq_irq)                   //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.reset_in1      (cpu_jtag_debug_module_reset_reset),  // reset_in1.reset
		.clk            (clocks_sys_clk_clk),                 //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.reset_in1      (cpu_jtag_debug_module_reset_reset),  // reset_in1.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_002 (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_002_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
